name: restaurant_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ... other dependencies
  rxdart: ^0.27.7 # Add this line
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  sqflite: ^2.0.0+4
  path_provider: ^2.0.8
  http: ^1.4.0 # Conservez la version la plus récente
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  fl_chart: ^0.68.0
  intl: ^0.19.0 # Gardez seulement une version
  image_picker: ^1.1.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/burger.jpg
    - assets/salad.jpg
    - assets/pizza.jpg
